source .nessie
source .qmg_encrypt
source .alias_profile
export PATH=$PATH:/opt/gradle/gradle-5.2.1/bin
source ~/git-completion.bash
export WORKON_HOME=~/pvenvs
source /usr/local/bin/virtualenvwrapper.sh
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH=$PATH:/usr/local/sbin
export PATH="/usr/local/opt/tomcat@7/bin:$PATH"
export METRICS_HOST=metrics-relay.dev.qmetric.co.uk
export METRICS_PORT=2003
export METRICS_NAMESPACE=dfarr
